/* GENERATED by tools/scripts/gen_static_ints.py from jadx sources of APK sha256 4800eac5...6bf4.
   public static final int constants of classes referenced by libgame.so. Do not edit by hand. */
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSITIAL_SIGNAL_AD_CLOSED", 3 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSITIAL_SIGNAL_AD_LOADED", 1 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSITIAL_SIGNAL_AD_OPENED", 2 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSITIAL_SIGNAL_ERROR", 4 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSTITIAL_PLATFORM_ERROR", 3 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSTITIAL_RESPONSE_INTERNAL_ERROR", 2 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSTITIAL_RESPONSE_INTERSTITIAL_NOT_VALID", 1 },
{ "com/backflipstudios/bf_ads/google_mobile_ads/InterstitialAd", "INTERSTITIAL_RESPONSE_SUCCESS", 0 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_core/information/InformationResponse", "PLATFORM_ERROR", 2 },
{ "com/backflipstudios/bf_core/information/InformationResponse", "REQUEST_IN_FLIGHT", 0 },
{ "com/backflipstudios/bf_core/information/InformationResponse", "UNAVAILABLE", 1 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "AdNotAvailable", 2 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "AdUnitMismatch", 3 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "InternalError", 5 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "PlatformError", 6 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "PreloadCancelled", 4 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "RequestInFlight", 0 },
{ "com/backflipstudios/bf_google_video_ads/GoogleVideoAdsResponse", "UserCancelled", 1 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_BAD_RESPONSE", 15 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_BILLING_SERVICE_NOT_AVAILABLE", 11 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_BILLING_UNAVAILABLE", 3 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_CANNOT_RETREIVE_APPLICATION", 20 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_DEVELOPER_ERROR", 5 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_ERROR", 6 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_INIT_NOT_REQUESTED", 14 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_INVALID_BUNDLE_RESPONSE_CODE", 13 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_INVALID_CONSUMPTION", 18 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_ITEM_ALREADY_OWNED", 7 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_ITEM_UNAVAILABLE", 4 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_JSON_EXCEPTION_PARSING_PURCHASE_DATA", 17 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_MAIN_ACTIVITY_NULL", 12 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_MISSING_PURCHASE_TOKEN", 19 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_NOT_OWNED", 8 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_NULL_DATA_RESPONSE_FOR_PURCHASE", 16 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_OK", 0 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_REMOTE_EXCEPTION", 21 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_REQUEST_IN_FLIGHT", 10 },
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_SERVICE_UNAVAILABLE", 2 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_SUBSCRIPTIONS_NOT_SUPPORTED", 9 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_iap/google/IAP", "IAP_RESPONSE_CODE_USER_CANCELED", 1 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_InternalError", 4 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_NotAvailable", 2 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_PlatformError", 5 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_RequestInFlight", 1 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_Success", 0 },
{ "com/backflipstudios/bf_notification/NotificationManager", "JavaResult_TokenRefreshFailed", 3 },
{ "com/backflipstudios/bf_ui/PlatformAlert", "INVALID", -1 },
{ "com/backflipstudios/bf_ui/PlatformAlert", "NEGATIVE", -2 },
{ "com/backflipstudios/bf_ui/PlatformAlert", "NEUTRAL", -3 },
{ "com/backflipstudios/bf_ui/PlatformAlert", "POSITIVE", -1 },
{ "com/backflipstudios/bf_ui/TextInput", "TEXT_INPUT_REPONSE_CODE_MAIN_ACTIVITY_NULL", 1 },
{ "com/backflipstudios/bf_ui/TextRenderingParams", "TEXT_RENDERING_ALIGNMENT_CENTER", 1 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_ui/TextRenderingParams", "TEXT_RENDERING_ALIGNMENT_LEFT", 0 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_ui/TextRenderingParams", "TEXT_RENDERING_ALIGNMENT_RIGHT", 2 }, /* name not in libgame strings */
{ "com/backflipstudios/bf_ui/UIResponse", "CANCELED", 2 },
{ "com/backflipstudios/bf_ui/UIResponse", "INTERNAL_ERROR", 3 },
{ "com/backflipstudios/bf_ui/UIResponse", "REQUEST_IN_FLIGHT", 1 },
{ "com/backflipstudios/bf_ui/WebView", "WEB_VIEW_REPONSE_CODE_MAIN_ACTIVITY_NULL", 1 },
